### PR TITLE
Fix captions check when display option is not defined

### LINKED ISSUE #145: Invalid position of the captions when tree object is used
As we can see in the [tree object sample](https://chartjs-chart-treemap.pages.dev/samples/tree.html), the captions are positioned correctly.

image

### PR DESCRIPTION
**Pull request by stockiNail**
Fix #145

### CODE REVIEW

File: src/element.js [hunk 1]
```diff
@@ -96,7 +96,7 @@ function addNormalRectPath(ctx, rect) {
 }
 
 export function shouldDrawCaption(rect, options) {
-  if (!options || !options.display) {
+  if (!options || (defined(options.display) && !options.display)) {
```
Comment (kurkle) [inline src/element.js:99]: Does it need to work with anything other than explicit `true`?
```suggestion
  if (!options || (options.display !== true) {
```

Comment (stockiNail) [reply src/element.js]: OK! let me update it because I need to remove the import as well. I was thinking to test herlpers.merge with the dataset.captions and the chart.options.elements.treemap. What do you think ? (not here, of course)

Comment (stockiNail) [reply src/element.js]: and rebase

Comment (kurkle) [reply src/element.js]: I'd avoid merging stuff. We should be using controller.options to access these, then the defaults are applied correctly.
Something like #121 (maybe I was too focused on scriptability and did not consider defaults at all)

Comment (stockiNail) [reply src/element.js]: I fully agree! Another new thing to me. I think that for dividers, captions, labels (not strictly related to an element) should be move to options.

Comment (stockiNail) [reply src/element.js]: > Does it need to work with anything other than explicit `true`?

It seems it doesn't work. Investigating....

Comment (stockiNail) [reply src/element.js]: The `"options.display !== true"` is wrong because, if `display` is not set, returns `true` but the default of `captions.display` is `true`.

Comment (stockiNail) [reply src/element.js:99]: Let me rollback your suggestion, rebase, and then let me check for another check even if I don't see many other ways.

Comment (kurkle) [reply src/element.js:101]: I'll have to take a look, I don't like having default handling all over the place. I'll check back later.

Meanwhile, if you can create a test catching the error, that would be good!

Comment (stockiNail) [reply src/element.js]: > I'll have to take a look, I don't like having default handling all over the place. I'll check back later.

ok, in the meanwhile changed in `if (!options || options.display === false) {`. I think the best thing is what you wrote above, to go to options instead of element defaults.

> Meanwhile, if you can create a test catching the error, that would be good!

`captionAlign.js` test fixture has been changed in this PR in order to reproduce the issue. I will create another fixture specific for this issue.

Comment (stockiNail) [reply src/element.js]: >  We should be using controller.options to access these, then the defaults are applied correctly.

I have created another branch to address this topic, following the other PR. Honestly, I don't see any fallback but maybe it depends on my lack of knowledge.

**Review by kurkle — APPROVED** [review]

**Comment by stockiNail** [comment]
@kurkle can I take time next week to have a look how the other controllers are working with defaults? I have quickly had a look to line controller which is using 2 options in the options and dataset, showLine and spanGap. I have seen something interesting. ok?

**Comment by stockiNail** [comment]
I see that `datasetElementType` is missing. I have tried adding it and setting to 'treemap'... I have the options as proxy and element defaults....

**Comment by stockiNail** [comment]
> datasetElement is the 2nd element tupe some controllers use. Its line for line controller (while dataElwmwnt is point). datasetElement is not needed here, though mainRect could be handled using it. I don't see any advantages in using it though.

I know that but I forgot to mention that line controller invokes `resolveDatasetElementOptions` in `update` method (where `datasetElementType` is needed).

The `resolveDatasetElementOptions` seems resolving the dataset options and therefore, after invocation, we have all fallbacks that we need (already tested).

**Comment by stockiNail** [comment]
ok, now I think I have understood how it should work and why you proposed to put the config in the options! ;)
Let me play a bit and then I'll submit a PR in draft to check if this is the best way.

**Comment by stockiNail** [comment]
Submitted #151. I think the idea to move all dataset options (or only the captions)  to `chart.options` could have the issue that if the user sets the `chart.options.elements.treemap`, the value that you have on options is not correct.
