### PR TITLE
Fix hovering on labels and captions

### LINKED ISSUE #149: hoverColor property for captions and labels not working
So hoverColor property for captions and labels not working. Color field works as expected but hoverColor is not. I found that using a function it is being called but the return value make nothing.

### PR DESCRIPTION
**Pull request by stockiNail**
Fix #149

### CODE REVIEW

File: src/element.js [hunk 1]
```diff
@@ -54,6 +54,7 @@ function boundingRects(rect, dpr) {
     y: bounds.top,
     w: width,
     h: height,
+    active: rect.active,
```
Comment (kurkle) [inline src/element.js:57]: Fix looks wrong to me, the bounding rects are not elements and should not have colors etc. So something else is wrong.

Comment (stockiNail) [reply src/element.js:57]: See https://github.com/kurkle/chartjs-chart-treemap/issues/149#issuecomment-1281269100

Comment (stockiNail) [reply src/element.js:57]: If we don't want to add to the bounding rects, we need to pass it as argument to draw labels and captions functions.

**Review by kurkle — APPROVED** [review]
