### PR TITLE
Fix alignment, improve speed

### LINKED ISSUE #156: When I zoom by chartjs-plugin-zoom library, the children of tree move on the screen, and the zooming speed is very slow in the mobile size.
### Discussed in https://github.com/kurkle/chartjs-chart-treemap/discussions/155

<div type='discussions-op-text'>

<sup>Originally posted by **mirzaeianfar** October 18, 2022</sup>
When I zoom by chartjs-plugin-zoom library, the children of tree move on the screen, and the zooming speed is very slow in the mobile size.
How can I avoid moving  the items of tree  and touch speed more in mobile size?

Untitled
</div>

### LINKED ISSUE #158: Misalignment with large dataset
@kurkle offtopic: I have seen that with many elements, `squarify` is not working well 100%! I'm going to open an issue asap.

image

_Originally posted by @stockiNail in https://github.com/kurkle/chartjs-chart-treemap/issues/157#issuecomment-1284369212_

### PR DESCRIPTION
**Pull request by kurkle**
Fix: #158

Probably fixes #156 but needs to be tested

A lot of fixtures needs to be updated (again, did it once already), will continue with this tomorrow.

### CODE REVIEW

File: src/controller.js [hunk 1]
```diff
@@ -63,90 +39,69 @@ function buildData(dataset, mainRect, dpr) {
...
 
-    if (!defined(this._useTree)) {
-      this._useTree = !!dataset.tree;
-    }
     const groups = dataset.groups || (dataset.groups = []);
     const key = dataset.key || '';
     const rtl = !!dataset.rtl;
+    const tree = dataset.tree || dataset.data;
+
+    const mainRect = {
```
Comment (stockiNail) [inline src/controller.js:90]: I think we could use the iScale and vScale dimensions instead of chartArea. This will enable the stacked axes and multi treemap datasets in the same chart. I don't see any performance issue.

Comment (kurkle) [reply src/controller.js:89]: Updated to use x/yScale

**Comment by kurkle** [comment]
> @kurkle off-topic: should we use `helpers/index.js` for common function or do you want to go to a structure like the plugin annotation?

I was thinking it would be the point where we import things. It can be split to maintainable parts but everything should be exported through the index to keep the helpers structure a separate concern.

**Comment by kurkle** [comment]
still not right, zoom does not work properly now. will take another evening.

**Comment by kurkle** [comment]
@stockiNail if you have some spare time, can you give this some tests? Its a little bit big change for a bug fix.

**Comment by stockiNail** [comment]
> if you have some spare time, can you give this some tests? Its a little bit big change for a bug fix.

Hopefully I will have time today... I'll pull the branch asap.

**Comment by stockiNail** [comment]
@kurkle apologize, what does "nvm" mean?

**Comment by kurkle** [comment]
> @kurkle apologize, what does "nvm" mean?

[never mind](https://www.dictionary.com/e/acronyms/nvm/#:~:text=NVM%20is%20an%20acronym%20that,often%20used%20as%20a%20hashtag.)

File: src/controller.js [hunk 2]
```diff
@@ -63,131 +39,111 @@ function buildData(dataset, mainRect, dpr) {
...
+    return {
+      min: scale.min || 0,
+      max: scale.max || (scale.axis === 'x' ? scale.right - scale.left : scale.bottom - scale.top)
+    };
+  }
+
+  configure() {
+    super.configure();
+    const {xScale, yScale} = this.getMeta();
+    if (!xScale || !yScale) {
```
Comment (stockiNail) [inline src/controller.js:78]: In my test case, locally, where I was testing the zoom, xScale and yScale are undefined here, therefore also this._rect.

Comment (kurkle) [reply src/controller.js:78]: Yes, turns out configure is only called once if the canvas is initially hidden or has zero size (which happens in the documentation for example).

Comment (kurkle) [reply src/controller.js:78]: I think I need to use `linkScales` instead

Comment (stockiNail) [reply src/controller.js:78]: The scales, in `linkScales`, don't have any dimension. The dimension is calculated during the `scale.update()`  therefore we should manage the size after `scale.update()`, therefore in the `controller.update()`, as was before, I guess.

Comment (stockiNail) [reply src/controller.js:78]: I see also a possible issue setting scale.min/max because this could overlap the values set by the plugin

Comment (stockiNail) [reply src/controller.js:78]: Sorry but I was busy in other stuff. What I meant is that when the zoom is "reset", the controller cannot recognize it.

Comment (kurkle) [reply src/controller.js:78]: Everything working in my local testing now, what do you think?

Comment (stockiNail) [reply src/controller.js:78]: Yes, it's working locally as well!! Thank you

Comment (stockiNail) [reply src/controller.js:78]: I have a couple of issues related to hoverCaption ane labelsMultilineFonts tolerance but doesn't matter. The rest seems working.

**Review by stockiNail — DISMISSED** [review]

File: src/controller.js (hunk 2 above)
Comment (stockiNail) [reply src/controller.js:78]: 2.1.3 or 2.2.0?

Comment (kurkle) [reply src/controller.js:78]: going with 2.1.3
